apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekart-deployment
  labels:
    app: ekart
spec:
  replicas: 2  # High availability kosam 2 pods run avthayi
  selector:
    matchLabels:
      app: ekart
  template:
    metadata:
      labels:
        app: ekart
    spec:
      containers:
      - name: ekart-container
        image: devpractice1/ekart:latest # Mee Docker Hub image
        imagePullPolicy: Always
        ports:
        - containerPort: 8070 # Mee application port
